puts "The students of my cohort at Makers Academy"
puts "------------"
puts "Bernard Mordan"
puts "Stephens Hat"
puts "Nicole Pell"
puts "Yvette Cook"
puts "Elena Garrone"
puts "Fadie"
puts "Tim"
puts "Ella Nancy Fay"
puts "Andrew Hercules"
puts "Camilla"
puts "Pablo"
puts "Rachel"
puts "Anna Schechter"
puts "Sandrine"